name: diy_social_app
description: A social DIY platform

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^6.2.1

  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0

  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # Video player
  video_player: ^2.8.2

  # State management
  provider: ^6.1.1

  # Navigation
  go_router: ^17.0.0
  flutterfire_cli: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/